### ISSUE TITLE
Python not found when want to "make update"- building blender add-on

### ISSUE THREAD

**Issue by Yoru66** [dillongoostudios/goo-blender#14]
Hello there I'am still new into this, so i dont know much about building this but anyways im currently trying to build the addon i got from github the "goo-engine". but im cant "make update" in my cmd command. Does anyone know how to fix this? I had been trying to fix this but still got no clue.

I already put slikssvn, cmake, and git-cmd, visual code, msvn onto the path. When i download cmake, i pick the "for all path" choice
I already had 

**the code:** 
C:\blendergoo-git\goo-engine>make update
Warning: Python not found, there is likely an issue with the library folder
No explicit msvc version requested, autodetecting version.
Compiler Detection failed. Use verbose switch for more information.
Visual Studio not found (try with the 'verbose' switch for more information)

C:\blendergoo-git\goo-engine>make verbose
Warning: Python not found, there is likely an issue with the library folder
svn    : "C:\Program Files\SlikSvn\bin\svn.exe"
cmake  : ""
ctest  : ""
git    : "C:\Program Files\Git\cmd\git.exe"
python : """"
No explicit msvc version requested, autodetecting version.
Detecting msvc 2019
Visual Studio 2019 is not detected
Detecting msvc 2022
Visual Studio 2022 is not detected
Compiler Detection failed. Use verbose switch for more information.
Visual Studio not found (try with the 'verbose' switch for more information)

**Comment by pftq** [comment]
Hello - for me, it failed to do "make update" until I did the following.  Can you check if that might apply in your case?
1) install [Git for Windows](https://gitforwindows.org/), not Github for Windows
2) install VC 2019 (not 2022).  Also make sure to check the option for C++ desktop development.

**Comment by TomerGamerTV** [comment]
Did you use the Git bash terminal?

**Comment by Yoru66** [comment]
@TomerGamerTV Hello there! , well for this part ..
_______
the code:
C:\blendergoo-git\goo-engine>make update
Warning: Python not found, there is likely an issue with the library folder
No explicit msvc version requested, autodetecting version.
Compiler Detection failed. Use verbose switch for more information.
Visual Studio not found (try with the 'verbose' switch for more information) 
_____
I wrote it on CMD. I'm not sure how to use the GitHub bash terminal

**Comment by TomerGamerTV** [comment]
> @TomerGamerTV Hello there! , well for this part ..
> 
> the code: C:\blendergoo-git\goo-engine>make update Warning: Python not found, there is likely an issue with the library folder No explicit msvc version requested, autodetecting version. Compiler Detection failed. Use verbose switch for more information. Visual Studio not found (try with the 'verbose' switch for more information)
> 
> I wrote it on CMD. I'm not sure how to use the GitHub bash terminal

fuck sorry i was on my phone and this stupid auto-correct messed it up. i meant Git bash cmd 
![image](https://user-images.githubusercontent.com/44266242/205489852-5900e5df-17b4-44b1-9b94-30eb92c9dbe8.png)

just do make update and after it finished type make.

the terminal might ask you to download more libraries so just type y and enter

**Comment by Yoru66** [comment]
if I may know, what should I write? (any youtube vids guideline maybe?). Im not sure how to do it on githuh bash.. I tried to used the same code i manage to succeed on the cmd terminal but it doesnt work the same it goes. "command not found"

(also I'm kinda hesistant to download visual studio code 2019, since that means i have to remove visual studio code 2022, just making sure but is the 2019 very neccesary in this case?, thank you!)

<img width="775" alt="image" src="https://user-images.githubusercontent.com/76588314/205490869-6d7618bf-fc2c-4195-8ca9-60980178bc1f.png">

**Comment by TomerGamerTV** [comment]
> if I may know, what should I write? (any youtube vids guideline maybe?). Im not sure how to do it on githuh bash.. I tried to used the same code i manage to succeed on the cmd terminal but it doesnt work the same it goes. "command not found"
> 
> (also I'm kinda hesistant to download visual studio code 2019, since that means i have to remove visual studio code 2022, just making sure but is the 2019 very neccesary in this case?, thank you!)
> 
> <img alt="image" width="775" src="https://user-images.githubusercontent.com/76588314/205490869-6d7618bf-fc2c-4195-8ca9-60980178bc1f.png">

want me to give you the installer? i already built it and can just send you. you will need to install visual studio if you want to build it yourself i don't think there is any other way to do it.

**Comment by Yoru66** [comment]
yes please that would be great!, if you are alright with it ofc

**Comment by TomerGamerTV** [comment]
> yes please that would be great!, if you are alright with it ofc

I forked this repo and put the installer in the [releases tab](https://github.com/TomerGamerTV/goo-engine/releases). It has builds for Mac and Windows so choose whatever you want.

**Comment by Yoru66** [comment]
> I forked this repo and put the installer in the [releases tab](https://github.com/TomerGamerTV/goo-engine/releases). It has builds for Mac and Windows so choose whatever you want.

@TomerGamerTV alright then thank you very much! I really appreciated your help!

**Comment by TomerGamerTV** [comment]
> > I forked this repo and put the installer in the [releases tab](https://github.com/TomerGamerTV/goo-engine/releases). It has builds for Mac and Windows so choose whatever you want.
> 
> 
> 
> @TomerGamerTV alright then thank you very much! I really appreciated your help! 

No problem 👍🏻

**Comment by diophants** [comment]
> Hello there I'am still new into this, so i dont know much about building this but anyways im currently trying to build the addon i got from github the "goo-engine". but im cant "make update" in my cmd command. Does anyone know how to fix this? I had been trying to fix this but still got no clue.
> 
> I already put slikssvn, cmake, and git-cmd, visual code, msvn onto the path. When i download cmake, i pick the "for all path" choice I already had
> 
> **the code:** C:\blendergoo-git\goo-engine>make update Warning: Python not found, there is likely an issue with the library folder No explicit msvc version requested, autodetecting version. Compiler Detection failed. Use verbose switch for more information. Visual Studio not found (try with the 'verbose' switch for more information)
> 
> C:\blendergoo-git\goo-engine>make verbose Warning: Python not found, there is likely an issue with the library folder svn : "C:\Program Files\SlikSvn\bin\svn.exe" cmake : "" ctest : "" git : "C:\Program Files\Git\cmd\git.exe" python : """" No explicit msvc version requested, autodetecting version. Detecting msvc 2019 Visual Studio 2019 is not detected Detecting msvc 2022 Visual Studio 2022 is not detected Compiler Detection failed. Use verbose switch for more information. Visual Studio not found (try with the 'verbose' switch for more information)

I managed to solve this problem!

1. I download "visual studio" (not "visual studio code"!)
2. In the Visual Studio installer, i additionally installed Python with all its dependencies (Python 3, Python web, etc...)
3. Restarted the computer

![image](https://github.com/dillongoostudios/goo-engine/assets/148638722/2c18f270-9ec1-4d91-872c-63f74628de95)

```
cd C:/blender-git/blender
.\make.bat update
```
Done!
