### ISSUE TITLE
is something wrong with my setup(always build error)

### ISSUE THREAD

**Issue by Askysoul** [dillongoostudios/goo-blender#22]
used 

visual studio 22 and visual studio 2019 both having same error when compiling

has python 3 and 2 has Cmake as system path and also for python

but when using make update it returns error(able to build the official blender without any issues)

Error in question 

Checked out revision 63162.
python not found, required for this operation

**Comment by Askysoul** [comment]
fixed it

**Comment by warior456** [comment]
you know it would be cool to say how you fixed it
