### ISSUE TITLE
Cloning submodules failed.

### ISSUE THREAD

**Issue by Yabusaki-KS47** [dillongoostudios/goo-blender#30]
![Code_QBkm58GFaJ](https://user-images.githubusercontent.com/91462300/226293243-07840382-fa57-4bd1-96f3-0e825589e659.png)
I do not know how to proceed. Any help is appreciated, thank you.

**Comment by lx-fox** [comment]
Had the same problem. It seams like the urls for the submodules changed. For a quick and dirty hack/fix you can go into the .git folder (hidden folder) and change the urls in the config file. Here is how i changed mine:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/dillongoostudios/goo-engine.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "goo-blender-master"]
	remote = origin
	merge = refs/heads/goo-blender-master
[submodule "release/datafiles/locale"]
	active = true
	url = https://projects.blender.org/blender/blender-translations.git
[submodule "release/scripts/addons"]
	active = true
	url = https://github.com/dillongoostudios/goo-blender-addons.git
[submodule "release/scripts/addons_contrib"]
	active = true
	url = https://projects.blender.org/blender/blender-addons-contrib.git
[submodule "source/tools"]
	active = true
	url = https://projects.blender.org/blender/blender-dev-tools.git

**Comment by Yabusaki-KS47** [comment]
OK I got through the error. Thanks a lot for your help.
