### ISSUE TITLE
Unable to build goo blender

### ISSUE THREAD

**Issue by zunedai** [dillongoostudios/goo-blender#5]
I've tried to compile blender a couple of times, but always run into an error
First, I'm using windows 10 with a Ryzen 5 3600, Nvidia GTX 1080 and 16gb ram

The steps I take are as follows

First, I installed VS 2022 Community edition (do I need the 2019 version?), which the Desktop Development with C++ workload and python
Then I installed SlikSVN, Git and CMake

I created a folder (D:\gooblender), open CMD with admin, navigate to the folder and use the following command:
git clone https://github.com/dillongoostudios/goo-engine
(Note, the same issue happens when I use goo-blender instead of goo-engine)

After it downloads, I go to the goo blender/engine folder and use the command:
_make update_

It goes through downloading all the LIB files in my gooblender folder (the root folder, not the goo-blender or goo-engine folder)

At the end, I get this error:
**Checked out revision 63091.
python not found, required for this operation**

The latest python is installed.

Next, I use the 'make' command and, at the end, get this error
**error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for release/scripts/addons**

When I run the command again, it does seem to actually start and go through the whole process
However, it either freezes completely or gives the following error in the build.log below
[Build.log](https://github.com/dillongoostudios/goo-engine/files/9946053/Build.log)

Failing that, I try doing the following
_make full nobuild_

It builds the files to be used for VS 2022

I open blender.sln
navigate to CMakePredefinedTargets>INSTALL and build that
Freeze again
Try running it again

I get this error
**error : Designtime build failed for project 'D:\gooblender\build_windows_Full_x64_vc17_Release\source\creator\blender.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate**.

or I get this error

**135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: The command "setlocal
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmEnd
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmErrorLevel
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: exit /b %1
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmDone
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
135>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :VCEnd" exited with code 1.
135>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 127 succeeded, 8 failed, 30 up-to-date, 0 skipped ==========**

Another errors I get is:
**error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for release/scripts/addons**
.
I have no idea what to do or what I'm missing here.

**Comment by VastyViz** [comment]
> Another errors I get is:
error: pathspec 'master' did not match any file(s) known to git
fatal: run_command returned non-zero status for release/scripts/addons

I'm new to this so I might speaking nonsense here but
Have you checked if D:\gooblender\goo-engine\release\scripts\addons contains any files? 
If not then try to copy it from this link - [addons](https://github.com/dillongoostudios/goo-blender-addons/tree/e3fc43ae15993abd19b5d6acb7f37b4616272b2e)

If addons_contrib is also empty then copy this as well [addons_contrib](https://github.com/blender/blender-addons-contrib/tree/95107484d076bc965239942e857c83433bfa86d7)

Same with release/datafiles/locale - [locale](https://github.com/blender/blender-translations/tree/a2eb507891449a0b67582be9561840075513661d)

#2

**Comment by abd-3d** [comment]
Same here.

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: The command "setlocal [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [C:\blender-git\build_
windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: :cmEnd [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\blender-git\build_windows_x64_vc17_Release\
INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: :cmErrorLevel [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: exit /b %1 [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: :cmDone [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): e
rror MSB3073: :VCEnd" exited with code 1. [C:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]

**Comment by katfacey** [comment]
ditto. i also get multiple similar errors as above when building goo blender.

**Comment by abd-3d** [comment]
"git clone https://github.com/dillongoostudios/goo-engine.git --recursive"
use this, it will install all dependencies and it work for me.

**Comment by katfacey** [comment]
> "git clone https://github.com/dillongoostudios/goo-engine.git --recursive" use this, it will install all dependencies and it work for me.

building still fails for me.
a fatal error ( LNK1120) is thrown when it tries to create blender.lib and blender.exp
build.log attached, the errors at the very bottom.
if anyone has success, could they walk through the steps they took?
[Build.log](https://github.com/dillongoostudios/goo-engine/files/9965043/Build.log)

**Comment by zunedai** [comment]
That fixed it for me! Thank you!
