### ISSUE TITLE
svn unable to install

### ISSUE THREAD

**Issue by plushrib** [dillongoostudios/goo-blender#50]
hello, recently i tried to build this engine but couldn't "make update". so i tried installing the recommended svn, TortoiseSVN. the website used to host it seems comply broken since most of the time it's down or wont let me install it. anyone know how to insall it?

**Comment by plushrib** [comment]
also why do you need to use svns anyways if it supports git?

**Comment by Javatrix** [comment]
Try using "winget install TortoiseSVN.TortoiseSVN"

**Comment by plushrib** [comment]
I fixed the problem by just dolwoad silksvn, still wonder what happend to tortoise.
