### ISSUE TITLE
different errors while compile is running ,result in fail to complete 

### ISSUE THREAD

**Issue by MADesign-CG** [dillongoostudios/goo-blender#52]
hello 
this is the result of trying and compile the source code , 
i have downloaded the zip file for the 3.6 release version , then i did a make update to download the library , i run the command prompt at the extracted zip file of the source code , then i got these errors during the build .
i have no major knowledge with compiling and stuff but this engine is worth the trouble ,these are screen shots of what i got .

![worning1](https://github.com/dillongoostudios/goo-engine/assets/133689501/f3c43a43-f2ed-40de-9887-bc44205d67ce)

![worning2](https://github.com/dillongoostudios/goo-engine/assets/133689501/b5a0e8c2-f2fd-49a3-bdfe-a8bc4360cad4)

![worning3](https://github.com/dillongoostudios/goo-engine/assets/133689501/762a4a3a-91a1-41a8-b8c2-f1a0ef76b934)

![worning4](https://github.com/dillongoostudios/goo-engine/assets/133689501/9fea1ccc-422e-4039-be25-be767b475d3a)

![worning5](https://github.com/dillongoostudios/goo-engine/assets/133689501/a1738c4e-3537-424f-af7d-2473ed7673ed)

![worning6](https://github.com/dillongoostudios/goo-engine/assets/133689501/d4a29a9a-8140-444c-92ef-ce3373b2fd78)

![worning7](https://github.com/dillongoostudios/goo-engine/assets/133689501/f607a9ac-bdac-4d1c-a37c-d84f02d07b2e)

![worning8](https://github.com/dillongoostudios/goo-engine/assets/133689501/2d3fbdfa-6535-4cb3-a0b9-cafbf270b51b)

![worning9](https://github.com/dillongoostudios/goo-engine/assets/133689501/e0d3dc88-eb74-4352-9761-648912530015)

i did a rebuild after using the git command but it seems there is still a problem ,less then before ,but still , same issue occur with the main branch as well 

![worning10](https://github.com/dillongoostudios/goo-engine/assets/133689501/a97b97e1-22a8-4172-a384-841397d2ca1e)

but one thing in common all the compile i tried even using the VS ends after this command . is this just a lib update required or something else , please help 

![worning11](https://github.com/dillongoostudios/goo-engine/assets/133689501/7c9af525-ba03-4010-b10f-fadfa68e60c5)

**Comment by Lateasusual** [comment]
Your visual studio version is out of date, use 2019 or 2022.

**Comment by MADesign-CG** [comment]
hello

thank you for the reply , but the visual studio i used is the 2022 , but
after i downgraded to 2019 it did compile , i still cant get to build
branches of the builds availble , but for now i will just enjoy what i got
, many thanks for this amazing work , and i will make sure to tag you guys
for this , everyone should use gooengine .
im sorry if my issue was not well formed or similair to others , i have no
idea on how to compile or program stuff , unless its mechanical realted
things .

thank you again
god speed
