### ISSUE TITLE
Error building on linux

### ISSUE THREAD

**Issue by Not-None** [dillongoostudios/goo-blender#72]
trying to build on linux mint followed the offical instructions on blender building and got the following error:

```
[100%] Linking CXX executable ../../bin/blender
/blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvInit'
/blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvGetConversionMatrix'
/blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvConvert'
collect2: error: ld returned 1 exit status
make[3]: *** [source/creator/CMakeFiles/blender.dir/build.make:577: bin/blender] Error 1
make[2]: *** [CMakeFiles/Makefile2:7670: source/creator/CMakeFiles/blender.dir/all] Error 2
make[1]: *** [Makefile:166: all] Error 2
make: *** [GNUmakefile:367: all] Error 2
```

**Comment by MrComexs** [comment]
I'm getting a similar error as well.

```[100%] Linking CXX executable ../../bin/blender
/home/comexs/goo-engine-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA:(.text+0xc07): error: undefined reference to 'SharpYuvInit'
/home/comexs/goo-engine-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA:(.text+0xc0e): error: undefined reference to 'SharpYuvGetConversionMatrix'
/home/comexs/goo-engine-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA:bject source/blender/nodes/geometry/CMakeFiles/bf_nodes_geometry.dir/Unity/unity_5_cxx.cxx.o       ned from ‘void ccl::shadow_linking_shade(KernelGlo
(.text+0xc99): error: undefined reference to 'SharpYuvConvert'
collect2: error: ld returned 1 exit status
make[3]: *** [source/creator/CMakeFiles/blender.dir/build.make:578: bin/blender] Error 1
make[2]: *** [CMakeFiles/Makefile2:7670: source/creator/CMakeFiles/blender.dir/all] Error 2
make[1]: *** [Makefile:166: all] Error 2
make: *** [GNUmakefile:367: all] Error 2
```

I followed this [guide](https://wiki.blender.org/wiki/Building_Blender/Linux/Arch) but I did this [instead](https://rentry.co/building-goo-engine-on-arch-linux). I didn't follow the Advanced setup.

**Comment by Not-None** [comment]
> trying to build on linux mint followed the offical instructions on blender building and got the following error:
> 
> ```
> [100%] Linking CXX executable ../../bin/blender
> /blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvInit'
> /blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvGetConversionMatrix'
> /blender-git/lib/linux_x86_64_glibc_228/webp/lib/libwebp.a(picture_csp_enc.c.o):picture_csp_enc.c:function ImportYUVAFromRGBA: error: undefined reference to 'SharpYuvConvert'
> collect2: error: ld returned 1 exit status
> make[3]: *** [source/creator/CMakeFiles/blender.dir/build.make:577: bin/blender] Error 1
> make[2]: *** [CMakeFiles/Makefile2:7670: source/creator/CMakeFiles/blender.dir/all] Error 2
> make[1]: *** [Makefile:166: all] Error 2
> make: *** [GNUmakefile:367: all] Error 2
> ```

The error was caused by building from goo-engine's main branch instead of the 4.0 branch hope this helps anyone with the same error [Goo Engine 4.0 Branch](https://github.com/dillongoostudios/goo-engine/tree/goo-engine-v4.0-release)
