### ISSUE TITLE
The mentioned youtube channel in the readme doesn't exist.

### ISSUE THREAD

**Issue by Ikxi1** [dillongoostudios/goo-blender#74]
The mentioned youtube channel in the readme doesn't exist.
![image](https://github.com/dillongoostudios/goo-engine/assets/69396495/01ae36cb-5d10-49b5-aa1a-50b12a7df031)

**Comment by thorn-neverwake** [comment]
https://youtube.com/@professorGoo

**Comment by Diordany** [comment]
There are two open pull requests that are related to this issue: [#67](https://github.com/dillongoostudios/goo-engine/pull/67) and [#73](https://github.com/dillongoostudios/goo-engine/pull/73).

**Comment by Ikxi1** [comment]
> There are two open pull requests that are related to this issue: [#67](https://github.com/dillongoostudios/goo-engine/pull/67) and [#73](https://github.com/dillongoostudios/goo-engine/pull/73).

Ahh ok, I have looked for "youtube" in issues and didn't seem them

**Comment by Diordany** [comment]
> > There are two open pull requests that are related to this issue: [#67](https://github.com/dillongoostudios/goo-engine/pull/67) and [#73](https://github.com/dillongoostudios/goo-engine/pull/73).
> 
> Ahh ok, I have looked for "youtube" in issues and didn't seem them

Oh I didn't mean to deny your issue, I'm not even involved with the project. I just wanted to point out to the maintainers that there are fixes available for this issue already.

**Comment by Diordany** [comment]
> > > There are two open pull requests that are related to this issue: [#67](https://github.com/dillongoostudios/goo-engine/pull/67) and [#73](https://github.com/dillongoostudios/goo-engine/pull/73).
> > 
> > 
> > Ahh ok, I have looked for "youtube" in issues and didn't seem them

Those are pull requests btw. This was the only issue I could find.
