### ISSUE TITLE
Screenspace info node just shows black for color channel ... tried in multiple scenes 

### ISSUE THREAD

**Issue by Ulf3000** [dillongoostudios/goo-blender#86]
what the title says.

the screenspace info node seems to be broken and just displays black for the color channel. 

anyone else get this bug ?

**Comment by thorn-neverwake** [comment]
Screenspace node has no issues for me on Windows, using the official Patreon version.

Works in 3.6, 4.0, and 4.1.

**Comment by Ulf3000** [comment]
> Screenspace node has no issues for me on Windows, using the official Patreon version.
> 
> Works in 3.6, 4.0, and 4.1.

any hidden setting i need to toggle ? 
can you attach a working example ?

**Comment by thorn-neverwake** [comment]
Well, you need to be sure refraction is turned on in both the material and the render settings.

People often overlook that one.

**Comment by Ulf3000** [comment]
> Well, you need to be sure refraction is turned on in both the material and the render settings.
> 
> People often overlook that one.


that was it! thanx a lot !
